    //------------------------------------------------------------------------------
    // <auto-generated>
    //     Этот код создан по шаблону.
    //
    //     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
    //     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
    // </auto-generated>
    //------------------------------------------------------------------------------

    namespace ООО__Валимо_.Entity
    {
        using System;
        using System.Collections.Generic;
    
        public partial class Product
        {
            [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
            public Product()
            {
                this.ProductInOrder = new HashSet<ProductInOrder>();
            }
    
            public int id { get; set; }
            public string name { get; set; }
            public int genre { get; set; }
            public int cost { get; set; }
            public double discount { get; set; }
            public string creator { get; set; }
            public string image { get; set; }
            public string imagePath { get; set; }
            public string description { get; set; }

            public decimal costWithDis { get; set; }

            public virtual Genre Genre1 { get; set; }
            [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
            public virtual ICollection<ProductInOrder> ProductInOrder { get; set; }
        }
    }
